[package]
name = "wasm"
version = "0.1.0"
authors = ["Johan Nicander <mr.johannicander@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
wasm-bindgen = "0.2"